name: Build and Release Flutter APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create App Skeleton
        run: flutter create flash_checker

      - name: Inject User Code
        run: cp lib/main.dart flash_checker/lib/main.dart

      - name: Add Storage Permissions and Fix SDK Version
        run: |
          sed -i '/<application/i \    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />\n    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />' flash_checker/android/app/src/main/AndroidManifest.xml
          sed -i 's/compileSdk = flutter.compileSdkVersion/compileSdk = 36/g' flash_checker/android/app/build.gradle.kts

      - name: Build APK
        run: |
          cd flash_checker
          flutter pub add "file_picker:^8.0.0"
          flutter build apk --release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          files: flash_checker/build/app/outputs/flutter-apk/app-release.apk
 
